try:
    raise AssertionError, 'this is a test'
except:
    print 'test passed'
